# Generated by Django 2.0.7 on 2018-09-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telefone',
        ),
    ]
