# Generated by Django 2.0.7 on 2018-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_remove_profile_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
