# Generated by Django 2.0.7 on 2018-09-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_ficha_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='countries',
        ),
    ]
