# Generated by Django 2.0.7 on 2018-09-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_remove_ficha_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='anotacoes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
