# Generated by Django 2.0.7 on 2018-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_auto_20180915_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ideal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='predito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
