# Generated by Django 2.0.7 on 2018-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_auto_20180916_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='n_adversos',
            new_name='bool_adversos',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='n_previa',
            new_name='bool_previo',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='adversos',
            new_name='e_adversos',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ajustado',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ideal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='predito',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
