# Generated by Django 2.0.7 on 2018-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_auto_20180921_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='bool_previo',
            field=models.BooleanField(default=False),
        ),
    ]
