# Generated by Django 2.0.7 on 2018-09-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_auto_20180921_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='bool_adversos',
            field=models.BooleanField(default=False),
        ),
    ]
