# Generated by Django 2.0.7 on 2018-09-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0008_auto_20180922_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='bool_adversos',
            new_name='bool_adverso',
        ),
    ]
