# Generated by Django 2.0.7 on 2018-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_auto_20180922_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='bool_alergias',
            field=models.BooleanField(default=False),
        ),
    ]
