# Generated by Django 2.0.7 on 2018-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_ficha_bool_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='alergias',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
