# Generated by Django 2.0.7 on 2018-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_auto_20180923_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='abd',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='acv',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='ar',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='ext',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='geral',
        ),
        migrations.AddField(
            model_name='ficha',
            name='bool_exfisico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficha',
            name='exfisico',
            field=models.TextField(blank=True, default='BEG, L.O.T.E., EUPNEICO, NORMOCORADO, HIDRATADO', max_length=500),
        ),
    ]
