# Generated by Django 2.0.7 on 2018-09-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0013_auto_20180923_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='exfisico',
            field=models.TextField(blank=True, default='Geral: B.E.G., L.O.T.E., eupnéico, normocorado, hidratado  /r sdadaadsds   ', max_length=500),
        ),
    ]
