# Generated by Django 2.0.7 on 2018-09-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0018_auto_20180923_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='exfisico',
            field=models.TextField(blank=True, default='Geral: B.E.G., L.O.T.E., eupnéico, normocorado, hidratado\nACV: Bulhas rítmicas, normofonéticas, em dois tempos, sem so', max_length=500),
        ),
    ]
