# Generated by Django 2.0.7 on 2018-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0019_auto_20180923_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='bool_doencas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='exfisico',
            field=models.TextField(blank=True, default='Geral: B.E.G., L.O.T.E., eupnéico, normocorado, hidratado\nACV: Bulhas rítmicas, normofonéticas, em dois tempos, sem sopros\nAR: Múrmurios vesiculares presentes bilateralmente, sem ruídos adventícios', max_length=500),
        ),
    ]
