# Generated by Django 2.0.7 on 2018-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0020_auto_20180925_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='cardio_neg',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='endocrino_neg',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='gastro_neg',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='hem_neg',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='musc_neg',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='neuro_neg',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='renal_neg',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='resp_neg',
        ),
        migrations.AddField(
            model_name='ficha',
            name='fa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ggt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='outros_lab',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tgo',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tgp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
