# Generated by Django 2.0.7 on 2018-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0024_auto_20180926_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='outroex',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
