# Generated by Django 2.0.7 on 2019-01-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0025_auto_20180929_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='resp_apn',
            field=models.BooleanField(default=False),
        ),
    ]
